// useContext Hook Code partially generated by chatGPT

import React, { createContext, useContext, useEffect, useState } from 'react'

const AuthContext = createContext();
export const AuthProvider = ({ children }) => {

  const [isLoggedIn, setIsLoggedIn] = useState(false);

  const login = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const handleFakeLogin = () => {
      // temp login logic
      if (email === 'demo@demo.com' && password === 'password') {
        setIsLoggedIn(true);
      }
    }

    const handleLogin = async () => {
      try {
        const response = await fetch('http://157.245.213.41:5000/api_login', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({ username, password }),
        });

        if (response.ok) {
          setIsLoggedIn(true);
        }
        else {
          setIsLoggedIn(false);
        }
      } catch (error) {
        // error
      }
    };

    // TODO: Login Logic - setIsLoggedIn(true);
  }

  const logout = () => {
    // TODO: Logout Logic - setIsLoggedIn(false);
  }

  return (
    <AuthContext.AuthProvider value={{ isLoggedIn, login, logout }}>
      {children}
    </AuthContext.AuthProvider>
  )
}

export const useAuth = () => {
  return useContext(AuthContext);
}
