// useContext Hook Code partially generated by chatGPT
import React, { useContext, useState } from 'react'

export const AuthProvider = ({ children }) => {

    const [isLoggedIn, setIsLoggedIn] = useState(false);

    const register = () => {
        const [name, setName] = useState('');
        const [address, setAddress] = useState('')
        const [email, setEmail] = useState('');
        const [phoneNumber, setPhoneNumber] = useState('');
        const [password, setPassword] = useState('');



        const handleFakeRegister = () => {
            // temp register logic
            if (username === 'demo' && password === 'password') {
                setIsLoggedIn(true);
            }
        }

        const handleRegister = async () => {
            try {
                const response = await fetch('http://157.245.213.41:5000/register', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ name, address, email, phoneNumber, password }),
                });

                if (response.ok) {
                    setIsLoggedIn(true);
                }
                else {
                    setIsLoggedIn(false);
                }
            } catch (error) {
                // error
            }
        };

        // TODO: Register Logic - setIsLoggedIn(true);
    }

    const logout = () => {
        // TODO: Logout Logic - setIsLoggedIn(false);
    }

    return (
        <AuthContext.AuthProvider value={{ isLoggedIn, register, logout }}>
            {children}
        </AuthContext.AuthProvider>
    )
}

export const useAuth = () => {
    return useContext(AuthContext);
}
