import Item from "../Types/Item";

// Descriptions Generated by ChatGPT

const menuItems: Item[] = [
    {
        "name": "Classic Burger",
        "description": "A juicy beef patty topped with lettuce, tomato, onions, and pickles, served in a soft bun.",
        "price": 5.69,
        "mod": [],
    },
    {
        "name": "Double Burger",
        "description": "Two succulent beef patties layered with cheese, lettuce, onions, and special sauce, all sandwiched between a toasted bun.",
        "price": 10.69,
        "mod": [],
    },
    {
        "name": "Classic Fries",
        "description": "Crispy golden fries seasoned with salt, served hot and fresh.",
        "price": 1.69,
        "mod": [],
    },
    {
        "name": "Cheesy Fries",
        "description": "Irresistible fries smothered in melted cheddar cheese and garnished with green onions.",
        "price": 4.20,
        "mod": [],
    },
    {
        "name": "Coca-Cola",
        "description": "A refreshing carbonated beverage, best served chilled with ice.",
        "price": 4.20,
        "mod": [],
    },
];


export default menuItems;